name: Report Elixir Coverage

on:
  workflow_run:
    workflows:
      - Elixir CI
    types:
      - completed

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  report-coverage:
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v8
        with:
          name: elixir-lcov
          path: ${{ runner.temp }}/cover
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - working-directory: ${{ runner.temp }}/cover
        run: |
          echo "PR_SHA=$(cat PR_SHA)" >> $GITHUB_ENV
          echo "PR_NUMBER=$(cat PR_NUMBER)" >> $GITHUB_ENV
      - uses: actions/checkout@v7 # UNTRUSTED CODE - do not run scripts from it
        with:
          ref: ${{ env.PR_SHA }}
      - name: Upload coverage artifact and post comment
        uses: mbta/github-actions-report-lcov@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-files: ${{ runner.temp }}/cover/lcov*.info
          artifact-name: elixir-code-coverage
